import { setItemPayload } from '@rescoped/components/datagrid';

export type SkyGridData = typeof skyGridData[number];

export const skyGridData = [
  setItemPayload(
    {
      date: '',
      airline: 'Astro Airlines',
      flightNumber: 'AA-1264',
      status: 'delayed',
      origin: 'Berlin',
      destination: 'London',
      duration: '1h 55min',
      estArrival: '10:30',
      estDeparture: '11:15',
      terminal: '2',
      gate: 'A09',
    },
    { actionType: 'row-single' },
  ),

  setItemPayload(
    {
      date: '15.10.2022',
      airline: 'Sky Fly',
      flightNumber: 'SF-5323',
      status: 'boarding',
      origin: 'Frankfurt',
      destination: 'Madrid',
      duration: '2h 40min',
      estArrival: '11:00',
      estDeparture: '11:45',
      terminal: '1',
      gate: 'C03',
    },
    { actionType: 'row-single' },
  ),
  setItemPayload(
    {
      date: '15.10.2022',
      airline: 'Central Ways',
      flightNumber: 'CW-1632',
      status: 'cancelled',
      origin: 'Munich',
      destination: 'Rome',
      duration: '1h 30min',
      estArrival: '11:15',
      estDeparture: 'cancelled',
      terminal: '2',
      gate: 'A07',
    },
    { actionType: 'row-single' },
  ),
  setItemPayload(
    {
      date: '16.10.2022',
      airline: 'Comfort Flights',
      flightNumber: 'CF-8532',
      status: 'scheduled',
      origin: 'London',
      destination: 'Istanbul',
      duration: '3h 55min',
      estArrival: '09:45',
      estDeparture: '10:30',
      terminal: '1',
      gate: 'B03',
    },
    { actionType: 'row-single' },
  ),
  setItemPayload(
    {
      date: '',
      airline: 'Venture airlines',
      flightNumber: 'VA-1424',
      status: 'scheduled',
      origin: 'Prague',
      destination: 'Brussel',
      duration: '1h 30min',
      estArrival: '12:00',
      estDeparture: '13:00',
      terminal: '1',
      gate: 'A07',
    },
    { actionType: 'row-single' },
  ),
  setItemPayload(
    {
      date: '16.10.2022',
      airline: 'Venture airlines',
      flightNumber: 'VA-1040',
      status: 'scheduled',
      origin: 'Prague',
      destination: 'Brussel',
      duration: '1h 30min',
      estArrival: '13:45',
      estDeparture: '14:50',
      terminal: '2',
      gate: 'B10',
    },
    { actionType: 'row-single' },
  ),
  setItemPayload(
    {
      date: '17.10.2022',
      airline: 'Sky Fly',
      flightNumber: 'SF-2042',
      status: 'scheduled',
      origin: 'Munich',
      destination: 'Rome',
      duration: '1h 30min',
      estArrival: '07:40',
      estDeparture: '08:30',
      terminal: '2',
      gate: 'C02',
    },
    { actionType: 'row-single' },
  ),
  setItemPayload(
    {
      date: '17.10.2022',
      airline: 'Central Ways',
      flightNumber: 'CW-2931',
      status: 'scheduled',
      origin: 'Hamburg',
      destination: 'Antalya',
      duration: '3h 55min',
      estArrival: '08:15',
      estDeparture: '09:10',
      terminal: '1',
      gate: 'A03',
    },
    { actionType: 'row-single' },
  ),
  setItemPayload(
    {
      date: '17.10.2022',
      airline: 'Astro Airlines',
      flightNumber: 'AA-1274',
      status: 'scheduled',
      origin: 'Hamburg',
      destination: 'Madrid',
      duration: '2h 10min',
      estArrival: '09:00',
      estDeparture: '10:00',
      terminal: '1',
      gate: 'B04',
    },
    { actionType: 'row-single' },
  ),
];
